# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7208e470bf843e2377066498a52abbfc6173ea12bd6fde86a6316bfd259f78cb2028701b576cdcd085b001381186a304b27d8cdad22a970713b7d95534b25935

test:
  secret_key_base: 50b311aa3b52ee1b59f3429ed32b37a9977536e5ac00cb123104ae31440fb950d1bc825c5dc25b3771622e44ba1204e5e26a90a1305ac8c4bba00528b91ed99b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
